apiVersion: v1
kind: Service
metadata:
  name: bwcemon-service
  labels:
    app: bwcemon
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: bwcemon

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: bwcemon
spec:
  replicas: 1
  selector:
    app: bwcemon
  template:
    metadata:
      name: bwcemon
      labels:
        app: bwcemon
    spec:
      containers:
        - name: bwcemon
        image: k3d-myregistry.localhost:12345/bwce-mon:2.7.2
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        imagePullPolicy: Always
        env:
        - name: PERSISTENCE_TYPE
          value:postgres
        - name: DB_URL
          value: postgres://<DB_USERNAME>:<PASSWORD>@<DB_IP>:<DB_PORT>/<DB_NAME>
        ports:
          - containerPort: 8080

