apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-bwce
spec:
  selector:
    matchLabels:
      app: hello-bwce
  template:
    metadata:
      labels:
        app: hello-bwce
    spec:
      containers:
      - name: hello-bwce
        image: k3d-myregistry.localhost:12345/helloworld:1.0.7
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8064
        env:
        - name: BW_JAVA_OPTS
          value: "-Dbw.engine.opentelemetry.enable=true -Dbw.frwk.event.subscriber.instrumention.enabled=true"
        - name: BW_PROFILE
          value: default
        - name: BW_LOGLEVEL
          value: INFO
        - name: BW_APP_MONITORING_CONFIG
          value: '{"url":"http://172.30.0.2:8888"}'
---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: ClusterIP
  selector:
    app: hello-bwce
  ports:
  - port: 88
    targetPort: 8064
    name: 80-8064
    protocol: TCP
--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-bwce-app
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-service
            port:
              number: 88

